# Generated by Django 5.0.4 on 2024-05-26 06:30

import users.utils.directory_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usermodel_groups_usermodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.directory_path.upload_path_user_avatar),
        ),
    ]
