# Generated by Django 5.0.6 on 2024-05-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
