# Generated by Django 5.0.4 on 2024-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
