# Generated by Django 5.0.6 on 2024-06-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_organization_classification_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
    ]
