# Generated by Django 5.0.4 on 2024-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_dead_line_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
