# Generated by Django 5.0.6 on 2024-07-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
        ('tasks', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='checklist',
            field=models.ManyToManyField(related_name='checklist', through='checklist.Checklist', to='checklist.product'),
        ),
    ]
